# news_data.py

# Live Global Financial News Module
ITEMS = [
    {
        "title": "UK Fintech Ayan Capital Secures $100 Million for Halal Digital Expansion",
        "date": "September 17, 2026",
        "desc": "British Islamic fintech firm Ayan Capital locked in a major £75 million ($100 million) Shariah-compliant financing facility managed by investment firm Triple Point. The funding accelerates their growth runway as they prepare their official digital banking licence applications."
    },
    {
        "title": "UAE Second Sovereign Dirham Sukuk Inundated by Diverse Investors",
        "date": "September 17, 2026",
        "desc": "The UAE Ministry of Finance announced details for its secondary domestic local-currency Sukuk auction following an inaugural rollout that drew subscriptions 9 times over target levels, showcasing substantial market depth among younger retail participants under 25."
    },
    {
        "title": "Philippines Central Bank Streamlines Shariah Bond Issuance Framework",
        "date": "September 11, 2026",
        "desc": "The Bangko Sentral ng Pilipinas (BSP) released a draft circular proposing a simplified regulatory system for local Islamic assets. The structural changes allow qualified domestic banking players to issue operations-focused Sukuk notes without intensive case-by-case prior approvals."
    }
]

# Educational Foundational Knowledge Hub Module
KNOWLEDGE = [
    {
        "term": "Sukuk (Islamic Certificates)",
        "concept": "Commonly referred to as 'Islamic Bonds'. Unlike conventional debt instruments that pay fixed interest (Riba), Sukuk certificates grant fractional ownership stakes in a tangible underlying physical asset, commercial venture, or investment project. Profits generated by the underlying asset are distributed as dividends."
    },
    {
        "term": "Murabaha (Cost-Plus Financing)",
        "concept": "An asset purchase arrangement where a financial institution buys a physical item (like a car or home) on behalf of a client and resells it to them at a clear, transparent cost-plus profit markup. Payment is made in staggered installments over time, entirely bypassing compounding loan interest lines."
    },
    {
        "term": "Mudarabah & Musharakah (Equity Pools)",
        "concept": "Mudarabah represents a joint venture profit-sharing structure where one partner provides the capital (Rab-al-Maal) and the other offers specialized labor expertise (Mudarib). Musharakah represents a deeply collaborative equity framework where all parties pool together both capital and management roles, sharing risks proportional to their capital inputs."
    }
]